[package]
name = "transaction_service"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = { version = "1.37.2", features = ["macros"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
